// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import QuizGameEditController from "./quiz_game/quiz_game_edit_controller"
import QuizGameShowController from "./quiz_game/quiz_game_show_controller"
import ClipboardController from "./clipboard_controller"

application.register("quiz_game_edit", QuizGameEditController)
application.register("quiz_game_show", QuizGameShowController)
application.register("clipboard", ClipboardController)


